@hostname = {{$dotenv HOST}}
@port = {{$dotenv PORT}}
@baseUrl = http://{{hostname}}:{{port}}

### Health Check
GET {{baseUrl}}/api/v1

### Recuperar todos los usuarios
# @name getAll
GET {{baseUrl}}/api/v1/users


### Recuperar el primer usuario
# @name getFirstUser
@firstUserId = {{ getAll.response.body.data.$[0].id }}
GET {{baseUrl}}/api/v1/users/{{firstUserId}}

### Recuperar el segundo usuario
# @name getSecondUser
@secondUserId = {{ getAll.response.body.data.$[1].id }}
GET {{baseUrl}}/api/v1/users/findById?id={{secondUserId}}

### Crear un usuario
POST {{baseUrl}}/api/v1/users
Content-Type: application/json

{
  "fullName": "Ctlase E2e",
  "jobArea": "tPruebas",
  "email": "tclase@hotmail.com"
}

### Actualizar el tercer usuario
# @name updateThirdUser
@thirdUserId = {{ getAll.response.body.data.$[2].id }}
PATCH  {{baseUrl}}/api/v1/users/{{thirdUserId}}
Content-Type: application/json

{
  "fullName": "David Chaum",
  "jobArea": "Cypherpunk's Father",
  "email": "David-Chaum@yahoo.com"
}

### Eliminar el primer usuario
@firstUserId = {{ getAll.response.body.data.$[0].id }}
DELETE  {{baseUrl}}/api/v1/users/{{firstUserId}}

### Crear un fecha con zona horaria
POST {{baseUrl}}/api/v1/dates
Content-Type: application/json

[
  {
    "timeZone": "America/Los_Angeles",
    "date": "2016-02-26T00:00:00-08:00"
  },
  {
    "timeZone": "America/Mexico_City",
    "date": "2016-02-26T12:15:00Z"
  },
  {
    "timeZone": "America/New_York",
    "date": "2016-02-26T00:00:00-05:00"
  },
  {
    "timeZone": "Europe/London",
    "date": "2016-02-26T00:00:00+00:00"
  }
]

### Recuperar todos los personajes
# @name getAll
GET {{baseUrl}}/api/v1/character?page=1

### Recuperar el detalle del personaje
# @name getAll
GET {{baseUrl}}/api/v1/character/4

### Recuperar un array de objetos 
# @name getAll
GET {{baseUrl}}/api/v1/character/2,4,6
