### Recuperar todos los usuarios
GET http://localhost:3000/api/v1/example

### Recuperar un usuario por path parameter
GET http://localhost:3000/api/v1/example/5ca97b7b-6a79-4202-94ae-d0bcee165ea4

### Recuperar un usuario por query parameter
GET http://localhost:3000/api/v1/example/findById?id=5ca97b7b-6a79-4202-94ae-d0bcee165ea4

### Crear un usuario
POST http://localhost:3000/api/v1/example
Content-Type: application/json

{
  "fullName": "Hal Finney",
  "jobArea": "Cypherpunk",
  "email": "Hal-Finney@yahoo.com",
  "isBlock": true
}

### Actualizar parcialmente a un usuario
PATCH  http://localhost:3000/api/v1/example/5ca97b7b-6a79-4202-94ae-d0bcee165ea4
Content-Type: application/json

{
  "fullName": "David Chaum",
  "jobArea": "Cypherpunk's Father",
  "email": "David-Chaum@yahoo.com"
}

### Eliminar un usuario por id
DELETE  http://localhost:3000/api/v1/example/5ca97b7b-6a79-4202-94ae-d0bcee165ea4
