services:
  api:
    image: ${HARBOR_REGISTRY}/${HARBOR_PROJECT}/${IMAGE_NAME}:latest
    pull_policy: always
    # Solo descomentar si se quiere construir la imagen localmente
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    # Eliminar command si el servicio no requiere base de datos
    command: sh -c 'until nc -z db 3306; do echo "Waiting for MySQL..."; sleep 2; done && npm run db:reset && pm2-runtime start ecosystem.config.js'
    labels:
      - "traefik.http.routers.${CI_PROJECT_NAME}-${IMAGE_NAME}-http.rule=Host(`${CI_PROJECT_NAME}-${IMAGE_NAME}.${HOST}`)||Host(`${CI_PROJECT_NAME}-${IMAGE_NAME}.${HOST}.patronato.unam.mx`)"
      - "traefik.http.routers.${CI_PROJECT_NAME}-${IMAGE_NAME}-http.entrypoints=web"
    env_file:
      - .env
    volumes:
      - app_logs:/opt/app/logs
    restart: on-failure:3
    networks:
      - proxy-net
    environment:
      - TZ=America/Mexico_City
    depends_on:
    - db
  db:
    image: mysql:8
    restart: on-failure:5
    environment:
      - MYSQL_DATABASE=mysqldb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=qwerty
      - MYSQL_ROOT_PASSWORD=qwerty
      - TZ=America/Mexico_City
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - proxy-net
volumes:
  app_logs:
    name: ${CI_PROJECT_NAME}-api-logs
  db_data:
    name: ${CI_PROJECT_NAME}-mysql-data
networks:
  proxy-net:
    external: true
